# Generated by Django 3.2 on 2022-04-04 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=200)),
                ('port', models.PositiveIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.country')),
            ],
        ),
        migrations.CreateModel(
            name='SmtpAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1200)),
                ('password', models.CharField(max_length=1200)),
                ('server', models.CharField(max_length=1200)),
                ('port', models.SmallIntegerField()),
                ('ssl', models.BooleanField(default=False)),
                ('connected', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'unique_together': {('profile', 'username', 'server', 'ssl')},
            },
        ),
        migrations.CreateModel(
            name='LinkedinAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=700)),
                ('password', models.CharField(max_length=700)),
                ('verification_code_url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=700, null=True)),
                ('avatar', models.ImageField(null=True, upload_to='linkedin-accounts/')),
                ('profile_url', models.URLField(null=True)),
                ('ready_for_use', models.BooleanField(default=False)),
                ('connected', models.BooleanField(default=False)),
                ('cookies_file_path', models.CharField(max_length=2000)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('proxy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_proxy', to='accounts.proxy')),
            ],
            options={
                'unique_together': {('username', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='GoogleAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=700)),
                ('email', models.EmailField(max_length=700)),
                ('refresh_token', models.CharField(max_length=777)),
                ('id_token', models.CharField(max_length=777)),
                ('access_token', models.CharField(max_length=777)),
                ('connected', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'unique_together': {('email', 'profile')},
            },
        ),
    ]
