# Generated by Django 3.2 on 2022-04-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='app_sumo_user',
            field=models.BooleanField(default=False),
        ),
    ]
