# Generated by Django 3.2 on 2022-04-11 20:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_app_sumo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('code', models.CharField(max_length=500, unique=True)),
                ('linkedin_and_email_accounts', models.IntegerField()),
                ('prospects_per_month', models.IntegerField()),
                ('white_label', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('license_product_key', models.UUIDField()),
                ('activation_email', models.EmailField(max_length=254)),
                ('invoice_item_uuid', models.UUIDField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.plan')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.license'),
        ),
    ]
