# Generated by Django 3.2 on 2022-05-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_whitelabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinaccount',
            name='headline',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
