# Generated by Django 3.2 on 2022-07-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220714_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='connection_requests_per_day_from',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='connection_requests_per_day_to',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emails_per_day_from',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emails_per_day_to',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inmails_per_day_from',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inmails_per_day_to',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='messages_per_day_from',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='messages_per_day_to',
            field=models.IntegerField(default=15),
        ),
    ]
