# Generated by Django 3.2 on 2022-07-19 19:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220719_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLinkedinAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('csv', models.FileField(upload_to='linkedin-account-imports/')),
                ('csv_name', models.CharField(max_length=700)),
                ('finished', models.BooleanField(default=False)),
                ('total_rows', models.PositiveIntegerField(default=1)),
                ('imported', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.TextField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
