# Generated by Django 3.2 on 2022-07-28 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_linkedinaccount_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinaccount',
            name='from_hour',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='linkedinaccount',
            name='to_hour',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
    ]
