# Generated by Django 3.2 on 2022-07-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220729_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinaccount',
            name='auto_accept_connection_requests',
            field=models.BooleanField(default=False),
        ),
    ]
