# Generated by Django 3.2 on 2022-07-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_linkedinaccount_auto_accept_connection_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinaccount',
            name='auto_accept_connection_requests_last_ran',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
