# Generated by Django 3.2 on 2022-08-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_linkedinaccount_auto_accept_connection_requests_last_ran'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinaccount',
            name='header_cookie',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkedinaccount',
            name='header_csrf_token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
