# Generated by Django 3.2 on 2022-08-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20220824_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinaccount',
            name='profile_urn',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
