# Generated by Django 3.2 on 2022-09-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_linkedinaccount_profile_urn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinaccount',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='linkedin-accounts/'),
        ),
        migrations.AlterField(
            model_name='linkedinaccount',
            name='headline',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='linkedinaccount',
            name='name',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='linkedinaccount',
            name='profile_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
