# Generated by Django 3.2 on 2022-09-16 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_whitelabel_ssl_generated'),
        ('accounts', '0022_auto_20220917_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinaccount',
            name='custom_proxy_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.country'),
        ),
        migrations.AddField(
            model_name='linkedinaccount',
            name='custom_proxy_password',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='linkedinaccount',
            name='custom_proxy_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedinaccount',
            name='custom_proxy_server',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='linkedinaccount',
            name='custom_proxy_username',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='linkedinaccount',
            name='use_custom_proxy',
            field=models.BooleanField(default=False),
        ),
    ]
