# Generated by Django 3.2 on 2022-04-04 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Waiting For User Connections', 'Waiting For User Connections'), ('Running', 'Running'), ('Finished', 'Finished'), ('Failed', 'Failed'), ('Stopped', 'Stopped')], default='Pending', max_length=28)),
                ('search_url', models.URLField(blank=True, max_length=900, null=True)),
                ('crawl_total_prospects', models.SmallIntegerField(default=25)),
                ('connection_requests_per_day', models.SmallIntegerField(default=10)),
                ('pages_crawled', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignLinkedinAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.campaign')),
                ('linkedin_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.linkedinaccount')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=0)),
                ('step', models.CharField(choices=[('send_connection_request', 'Send Connection Request'), ('send_message', 'Send Message'), ('send_inmail', 'Send InMail'), ('like_3_posts', 'Like 3 Posts'), ('follow', 'Follow'), ('endorse_top_5_skills', 'Endorse Top 5 Skills'), ('send_email', 'Send Email')], max_length=50)),
                ('note', models.TextField(blank=True, help_text='For Sending Connection Request', max_length=299, null=True)),
                ('message', models.TextField(blank=True, help_text='For Sending Message', max_length=7999, null=True)),
                ('inmail_subject', models.TextField(blank=True, help_text='For Sending InMail Message', max_length=200, null=True)),
                ('inmail_message', models.TextField(blank=True, help_text='For Sending InMail Message', max_length=486, null=True)),
                ('from_email', models.EmailField(blank=True, help_text='For Sending Email Only For SMTP', max_length=254, null=True)),
                ('email_subject', models.TextField(blank=True, help_text='For Sending Email', max_length=200, null=True)),
                ('email_message', models.TextField(blank=True, help_text='For Sending Email', max_length=700, null=True)),
                ('delay_in_hours', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.campaign')),
                ('google_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.googleaccount')),
                ('smtp_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.smtpaccount')),
            ],
            options={
                'unique_together': {('order', 'campaign')},
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('headline', models.CharField(blank=True, max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('linkedin_profile_url', models.URLField(blank=True, null=True)),
                ('linkedin_sales_navigator_profile_url', models.URLField(blank=True, null=True)),
                ('linkedin_avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('fully_crawled', models.BooleanField(default=False)),
                ('connection_request_sent', models.BooleanField(default=False)),
                ('connected', models.BooleanField(default=False)),
                ('show_inside_inbox', models.BooleanField(default=False)),
                ('state_status', models.CharField(blank=True, choices=[('Performing', 'Performing'), ('Failed', 'Failed'), ('Finished', 'Finished')], max_length=40, null=True)),
                ('state_action_start_time', models.DateTimeField(blank=True, null=True)),
                ('state_action_finish_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_linkedin_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.campaignlinkedinaccount')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.campaignsequence')),
            ],
        ),
        migrations.CreateModel(
            name='UserLinkedinConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_profile_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.campaignlinkedinaccount')),
                ('linkedin_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.linkedinaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SearchParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('Country', 'Country'), ('Connections', 'Connections'), ('Headline', 'Headline')], max_length=30)),
                ('value', models.CharField(max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_thread', models.URLField()),
                ('platform', models.CharField(choices=[('Linkedin', 'Linkedin'), ('Linkedin Sales', 'Linkedin Sales')], max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.prospect')),
            ],
            options={
                'unique_together': {('prospect', 'message_thread', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_from', models.CharField(choices=[('Prospect', 'Prospect'), ('User', 'User')], max_length=8)),
                ('time', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.room')),
            ],
        ),
        migrations.CreateModel(
            name='CeleryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField()),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Failed', 'Failed'), ('Finished', 'Finished')], default='Running', max_length=20)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignFailedReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.campaign')),
            ],
        ),
    ]
