# Generated by Django 3.2 on 2022-04-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='headline',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='linkedin_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.linkedinaccount'),
        ),
        migrations.AddField(
            model_name='room',
            name='linkedin_profile_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('linkedin_account', 'message_thread', 'platform')},
        ),
        migrations.RemoveField(
            model_name='room',
            name='prospect',
        ),
    ]
