# Generated by Django 3.2 on 2022-04-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220406_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='linkedin_avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
