# Generated by Django 3.2 on 2022-04-13 18:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_room_linkedin_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailWebHook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.prospect')),
            ],
        ),
    ]
