# Generated by Django 3.2 on 2022-04-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_emailwebhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsequence',
            name='delay_in_days',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
