# Generated by Django 3.2 on 2022-04-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_campaignsequence_delay_in_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='first_name',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='last_name',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='occupation',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='occupation_company_name',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='occupation_time',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='school_university',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
