# Generated by Django 3.2 on 2022-04-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220428_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospect',
            old_name='occupation_company_name',
            new_name='current_company',
        ),
        migrations.AddField(
            model_name='prospect',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='name',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
