# Generated by Django 3.2 on 2022-04-27 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220428_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='occupation_time',
        ),
    ]
