# Generated by Django 3.2 on 2022-04-29 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_room_customer_message_readed'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='prospect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.prospect'),
        ),
    ]
