# Generated by Django 3.2 on 2022-04-30 17:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_label'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('name', 'user')},
        ),
    ]
