# Generated by Django 3.2 on 2022-05-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_prospectlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
