# Generated by Django 3.2 on 2022-05-11 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20220511_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectlabel',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospect_labels', to='main.prospect'),
        ),
    ]
