# Generated by Django 3.2 on 2022-07-18 18:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_prospectlabel_prospect'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(choices=[('send_connection_request', 'Send Connection Request'), ('send_message', 'Send Message'), ('send_inmail', 'Send InMail'), ('like_3_posts', 'Like 3 Posts'), ('follow', 'Follow'), ('endorse_top_5_skills', 'Endorse Top 5 Skills'), ('send_email', 'Send Email')], max_length=23)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.prospect')),
            ],
        ),
    ]
