# Generated by Django 3.2 on 2022-07-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_prospectactionlog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='connection_requests_per_day',
        ),
    ]
