# Generated by Django 3.2 on 2022-07-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_campaign_connection_requests_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='last_runned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
