# Generated by Django 3.2 on 2022-07-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_campaign_last_runned_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='last_runned_at',
        ),
        migrations.AddField(
            model_name='campaignlinkedinaccount',
            name='last_runned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
