# Generated by Django 3.2 on 2022-07-29 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220729_0200'),
        ('main', '0021_auto_20220728_0146'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlinkedinconnection',
            unique_together={('linkedin_account', 'linkedin_profile_url')},
        ),
    ]
