# Generated by Django 3.2 on 2022-08-02 22:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_userlinkedinconnection_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryJobsLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('celery_job', models.UUIDField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField()),
                ('error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('action', models.CharField(choices=[('perform_campaign_actions', 'perform_campaign_actions'), ('check_user_connections', 'check_user_connections'), ('run_auto_accept_connection_requests', 'run_auto_accept_connection_requests'), ('run_campaigns', 'run_campaigns'), ('run_check_reply_and_get_conversations', 'run_check_reply_and_get_conversations')], max_length=37)),
            ],
        ),
    ]
