# Generated by Django 3.2 on 2022-08-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_celeryjobslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celeryjobslog',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
