# Generated by Django 3.2 on 2022-08-09 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_celeryjobslog_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celeryjobslog',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
