# Generated by Django 3.2 on 2022-08-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_celeryjobslog_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='type',
            field=models.CharField(choices=[('outreach', 'outreach'), ('post', 'post')], default='outreach', max_length=8),
        ),
    ]
