# Generated by Django 3.2 on 2022-08-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20220816_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcampaignpost',
            name='post_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
