# Generated by Django 3.2 on 2022-08-15 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_postcampaignpost_post_link'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postcampaignpost',
            unique_together={('campaign_linkedin_account', 'state')},
        ),
    ]
