# Generated by Django 3.2 on 2022-08-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_postcampaignpost_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostCampaignPost',
            new_name='EngagementCampaignPost',
        ),
    ]
