# Generated by Django 3.2 on 2022-08-18 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rename_postcampaignpost_engagementcampaignpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsequence',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='post-documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'ppt', 'pptx'])]),
        ),
    ]
