# Generated by Django 3.2 on 2022-08-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20220819_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postsequence',
            old_name='address',
            new_name='event_address',
        ),
        migrations.RenameField(
            model_name='postsequence',
            old_name='end_date_time',
            new_name='event_end_date_time',
        ),
        migrations.RenameField(
            model_name='postsequence',
            old_name='external_event_link',
            new_name='event_external_event_link',
        ),
        migrations.RenameField(
            model_name='postsequence',
            old_name='speakers',
            new_name='event_speakers',
        ),
        migrations.RenameField(
            model_name='postsequence',
            old_name='start_date_time',
            new_name='event_start_date_time',
        ),
        migrations.RenameField(
            model_name='postsequence',
            old_name='venue',
            new_name='event_venue',
        ),
        migrations.AddField(
            model_name='postsequence',
            name='event_format',
            field=models.CharField(blank=True, choices=[('LinkedIn Audio Event', 'LinkedIn Audio Event'), ('LinkedIn Live', 'LinkedIn Live'), ('External event link', 'External event link')], help_text='For Posting A Event With Event Format * (Required)', max_length=20, null=True),
        ),
    ]
