# Generated by Django 3.2 on 2022-08-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20220819_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postsequence',
            old_name='company',
            new_name='job_company',
        ),
        migrations.RenameField(
            model_name='postsequence',
            old_name='workplace_type',
            new_name='job_workplace_type',
        ),
        migrations.AddField(
            model_name='postsequence',
            name='job_location',
            field=models.TextField(blank=True, help_text='For Posting A Job With A Job Location', max_length=486, null=True),
        ),
    ]
