# Generated by Django 3.2 on 2022-08-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20220820_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsequence',
            name='employee_location',
            field=models.TextField(blank=True, help_text='For Posting A Job With A Employee Location', max_length=486, null=True),
        ),
    ]
