# Generated by Django 3.2 on 2022-08-22 20:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_prospect_engagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='engagement',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Liked Posts', 'Liked Posts'), ('Commented Posts', 'Commented Posts'), ('Shared Posts', 'Shared Posts'), ('Job Applicant', 'Job Applicant'), ('Event Attendee', 'Event Attendee')], max_length=69, null=True),
        ),
    ]
