# Generated by Django 3.2 on 2022-08-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_prospect_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='entity_urn',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
