# Generated by Django 3.2 on 2022-08-29 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20220824_0042'),
        ('main', '0040_prospect_entity_urn'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLinkedinGorup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linkedin_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.linkedinaccount')),
            ],
            options={
                'unique_together': {('linkedin_account', 'url')},
            },
        ),
    ]
