# Generated by Django 3.2 on 2022-08-29 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20220824_0042'),
        ('main', '0041_userlinkedingorup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLinkedinGorup',
            new_name='UserLinkedinGroup',
        ),
    ]
