# Generated by Django 3.2 on 2022-08-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_rename_userlinkedingorup_userlinkedingroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlinkedingroup',
            name='group_urn',
            field=models.CharField(default='', max_length=700),
            preserve_default=False,
        ),
    ]
