# Generated by Django 3.2 on 2022-08-30 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_userlinkedingroup_group_urn'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsequence',
            name='post_on',
            field=models.CharField(choices=[('Linkedin Profile', 'Linkedin Profile'), ('Linkedin Group', 'Linkedin Group')], default='Linkedin Profile', max_length=16),
        ),
        migrations.AddField(
            model_name='postsequence',
            name='post_on_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userlinkedingroup'),
        ),
    ]
