# Generated by Django 3.2 on 2022-09-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20220831_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsequence',
            name='wait_for_connection_request_to_be_approved',
            field=models.BooleanField(null=True, default=None),
        ),
    ]
