# Generated by Django 3.2 on 2022-09-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_campaignsequence_wait_for_connection_request_to_be_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignsequence',
            name='wait_for_connection_request_to_be_approved',
            field=models.BooleanField(default=True),
        ),
    ]
