# Generated by Django 3.2 on 2022-04-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
