# Generated by Django 3.2 on 2022-04-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_whitelabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelabel',
            name='domain',
            field=models.URLField(unique=True),
        ),
    ]
