# Generated by Django 3.2 on 2022-04-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_whitelabel_domain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whitelabel',
            options={},
        ),
    ]
