# Generated by Django 3.2 on 2022-04-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_whitelabel_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabel',
            name='primary_dark_color',
            field=models.CharField(default='#2E2E2E', max_length=7),
            preserve_default=False,
        ),
    ]
