# Generated by Django 3.2 on 2022-04-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_whitelabel_primary_dark_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabel',
            name='ssl_generated',
            field=models.BooleanField(default=False),
        ),
    ]
